"""add review

Revision ID: 1ad87e80e607
Revises: f32d460fc364
Create Date: 2024-06-27 19:55:50.356950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad87e80e607'
down_revision = 'f32d460fc364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['reviews.id'], name=op.f('fk_reviews_customer_id_reviews')),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_items_item_id_reviews'), 'items', 'reviews', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_items_item_id_reviews'), 'items', type_='foreignkey')
    op.drop_column('items', 'item_id')
    op.drop_table('reviews')
    # ### end Alembic commands ###
