"""add review

Revision ID: 94cd620118aa
Revises: 1ad87e80e607
Create Date: 2024-07-03 23:13:02.759169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cd620118aa'
down_revision = '1ad87e80e607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'item_id')
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_reviews_customer_id_reviews', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_customer_id_reviews', 'reviews', 'reviews', ['customer_id'], ['id'])
    op.drop_column('reviews', 'item_id')
    op.add_column('items', sa.Column('item_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
